import json
import math
import os
import random
import re
import sys
import time
import traceback
from dataclasses import dataclass, field
from typing import Any, Dict, Iterable, List, Optional, Tuple

try:
    # We attempt to import OpenAI at module import time, but handle absence gracefully.
    from openai import OpenAI  # type: ignore
except Exception:
    OpenAI = None  # type: ignore


def get_openai_api_key():
    api_key = os.environ.get("OPENAI_API_KEY")
    if api_key:
        return api_key
    raise ValueError("OpenAI API key not found in environment")


def call_gpt5_with_responses_api(prompt: str, model: str = "gpt-5", max_output_tokens: int = 4000) -> str:
    """
    Invoke OpenAI Responses API to get text output for the given prompt.
    If API or network fails, falls back to a deterministic templated output.
    """
    try:
        api_key = get_openai_api_key()
        if OpenAI is None:
            raise RuntimeError("openai package not installed")
        client = OpenAI(api_key=api_key)

        responses_kwargs = {
            "model": model,
            "input": [
                {"role": "user", "content": [{"type": "input_text", "text": prompt}]}
            ],
            "max_output_tokens": max_output_tokens,
        }

        resp = client.responses.create(**responses_kwargs)

        def extract_response(resp_obj):
            if hasattr(resp_obj, "output_text") and isinstance(resp_obj.output_text, str):
                return resp_obj.output_text
            try:
                output = getattr(resp_obj, "output", None)
                if output and isinstance(output, list):
                    content = output[0].get("content") if isinstance(output[0], dict) else None
                    if content and isinstance(content, list) and len(content) > 0:
                        text = content[0].get("text")
                        if isinstance(text, str):
                            return text
            except Exception:
                pass
            return str(resp_obj)

        return extract_response(resp)
    except Exception:
        # Fallback deterministic response to keep pipeline running offline
        return (
            "This is a synthesized review generated by a local fallback because the LLM "
            "service is unavailable. The content adheres to the plan and platform policy. "
            "Pros: specific aspects addressed; Cons: none major observed. Overall, a solid experience."
        )


# ------------------------------
# Utilities and helpers
# ------------------------------

def set_global_seed(seed: int) -> None:
    random.seed(seed)
    try:
        import numpy as np  # type: ignore
        np.random.seed(seed)
    except Exception:
        pass


def ensure_dir(path: str) -> None:
    d = os.path.dirname(os.path.abspath(path))
    if d and not os.path.exists(d):
        os.makedirs(d, exist_ok=True)


def write_json(path: str, obj: Any) -> None:
    ensure_dir(path)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2, ensure_ascii=False)


def write_jsonl(path: str, records: Iterable[Dict[str, Any]]) -> None:
    ensure_dir(path)
    with open(path, "w", encoding="utf-8") as f:
        for r in records:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")


def tokenize(text: str) -> List[str]:
    tokens = re.findall(r"[a-zA-Z']+", text.lower())
    return tokens


POS_WORDS = set("""
amazing awesome great excellent fantastic love loved good nice wonderful perfect thrilled satisfied delighted sturdy durable comfortable sleek elegant efficient fast smooth reliable tasty flavorful fresh crisp juicy convenient helpful friendly polite responsive
""".strip().split())
NEG_WORDS = set("""
bad terrible awful horrible disappointed disappointing poor slow broken flimsy cheap hate hated worst dirty noisy rude unhelpful late leaking damaged unusable confusing buggy crash crashes laggy bitter stale bland soggy
""".strip().split())


def sentiment_score(text: str) -> float:
    """
    Simple polarity score in [0,1] computed from token counts.
    """
    toks = tokenize(text)
    if not toks:
        return 0.5
    pos = sum(1 for t in toks if t in POS_WORDS)
    neg = sum(1 for t in toks if t in NEG_WORDS)
    total = pos + neg
    if total == 0:
        return 0.5
    score = (pos - neg) / max(1, total)
    # map [-1,1] to [0,1]
    return 0.5 * (score + 1.0)


def jaccard_similarity(a: str, b: str) -> float:
    sa, sb = set(tokenize(a)), set(tokenize(b))
    if not sa and not sb:
        return 1.0
    if not sa or not sb:
        return 0.0
    inter = len(sa & sb)
    union = len(sa | sb)
    return inter / max(1, union)


def sentence_count(text: str) -> int:
    sents = re.split(r"[.!?]+", text.strip())
    return max(0, len([s for s in sents if s.strip()]))


# ------------------------------
# Data structures
# ------------------------------

@dataclass
class InteractionRecord:
    user_id: str
    item_id: str
    stars: Optional[int] = None
    review: Optional[str] = None
    datatype: Optional[str] = None
    timestamp: Optional[float] = None


# ------------------------------
# Data Indexer
# ------------------------------

@dataclass
class DataIndexer:
    records: List[InteractionRecord]
    user_index: Dict[str, List[int]] = field(default_factory=dict)
    item_index: Dict[str, List[int]] = field(default_factory=dict)
    split_index: Dict[str, List[int]] = field(default_factory=dict)
    aspect_vocab: List[str] = field(default_factory=list)
    platform_policy: Dict[str, Any] = field(default_factory=dict)
    user_priors: Dict[str, float] = field(default_factory=dict)
    item_priors: Dict[str, float] = field(default_factory=dict)
    global_mean: float = 3.5

    @staticmethod
    def load_from_file_or_synthetic(path: str = "interactions.jsonl", seed: int = 7) -> "DataIndexer":
        set_global_seed(seed)
        records: List[InteractionRecord] = []
        if os.path.exists(path):
            try:
                with open(path, "r", encoding="utf-8") as f:
                    for line in f:
                        if not line.strip():
                            continue
                        d = json.loads(line)
                        rec = InteractionRecord(
                            user_id=str(d.get("user_id")),
                            item_id=str(d.get("item_id")),
                            stars=int(d["stars"]) if "stars" in d and d["stars"] is not None else None,
                            review=d.get("review"),
                            datatype=d.get("datatype"),
                            timestamp=float(d["timestamp"]) if "timestamp" in d and d["timestamp"] is not None else None,
                        )
                        records.append(rec)
            except Exception as e:
                print(f"Error reading {path}: {e}", file=sys.stderr)
                records = []
        if not records:
            # synthetic minimal dataset
            synth = [
                {"user_id": "u1", "item_id": "i1", "stars": 5, "review": "Amazing quality and fast delivery. Very satisfied!", "datatype": "train"},
                {"user_id": "u1", "item_id": "i2", "stars": 4, "review": "Good value and decent performance.", "datatype": "train"},
                {"user_id": "u2", "item_id": "i1", "stars": 3, "review": "Okay overall, design could be better.", "datatype": "train"},
                {"user_id": "u2", "item_id": "i3", "stars": 2, "review": "Slow and somewhat disappointing build.", "datatype": "test"},
                {"user_id": "u3", "item_id": "i2", "stars": 1, "review": "Terrible experience, broken on arrival and unhelpful support.", "datatype": "test"},
            ]
            records = [InteractionRecord(**d) for d in synth]
        di = DataIndexer(records=records)
        di._build_indices()
        di._compute_priors()
        di.aspect_vocab = [
            "quality", "price", "value", "design", "durability", "performance", "delivery", "packaging",
            "usability", "features", "battery", "size", "comfort", "customer_service"
        ]
        di.platform_policy = {
            "style": "concise, specific, respectful, no profanity",
            "min_sentences": 2,
            "max_sentences": 6,
            "profanity_list": [],
        }
        return di

    def _build_indices(self) -> None:
        self.user_index.clear()
        self.item_index.clear()
        self.split_index.clear()
        for idx, r in enumerate(self.records):
            self.user_index.setdefault(r.user_id, []).append(idx)
            self.item_index.setdefault(r.item_id, []).append(idx)
            split = r.datatype if r.datatype in ("train", "test") else None
            if split:
                self.split_index.setdefault(split, []).append(idx)
        # if no split labels, do random split 80/20
        if not self.split_index:
            indices = list(range(len(self.records)))
            random.shuffle(indices)
            cut = int(0.8 * len(indices))
            self.split_index["train"] = indices[:cut]
            self.split_index["test"] = indices[cut:]

    def _compute_priors(self) -> None:
        # Compute user/item priors from available labeled data
        user_s: Dict[str, List[int]] = {}
        item_s: Dict[str, List[int]] = {}
        stars_all: List[int] = []
        for r in self.records:
            if r.stars is not None:
                user_s.setdefault(r.user_id, []).append(r.stars)
                item_s.setdefault(r.item_id, []).append(r.stars)
                stars_all.append(r.stars)
        self.global_mean = sum(stars_all) / len(stars_all) if stars_all else 3.5
        self.user_priors = {u: (sum(v) / len(v)) for u, v in user_s.items()}
        self.item_priors = {i: (sum(v) / len(v)) for i, v in item_s.items()}

    def get_user_history_texts(self, user_id: str) -> List[str]:
        return [self.records[i].review or "" for i in self.user_index.get(user_id, []) if self.records[i].review]

    def get_item_history_texts(self, item_id: str) -> List[str]:
        return [self.records[i].review or "" for i in self.item_index.get(item_id, []) if self.records[i].review]

    def get_user_prior(self, user_id: str) -> float:
        return self.user_priors.get(user_id, self.global_mean)

    def get_item_prior(self, item_id: str) -> float:
        return self.item_priors.get(item_id, self.global_mean)


# ------------------------------
# Persona Profiler
# ------------------------------

@dataclass
class PersonaProfile:
    user_id: str
    baseline_leniency: float
    verbosity_prior: float
    tone_style_prior: str
    domain_familiarity: float
    leniency_drift: float
    aspect_preference_weights: Dict[str, float]
    style_vector: Dict[str, float]
    recent_sentiment_bias: float


class PersonaProfiler:
    def __init__(self, indexer: DataIndexer):
        self.indexer = indexer

    def build(self, user_id: str, neighbor_weight: float = 0.0) -> PersonaProfile:
        texts = self.indexer.get_user_history_texts(user_id)
        baseline = self.indexer.get_user_prior(user_id)
        # aspect preferences by counting mentions
        aspect_weights: Dict[str, float] = {a: 0.0 for a in self.indexer.aspect_vocab}
        for t in texts:
            toks = tokenize(t)
            for a in self.indexer.aspect_vocab:
                if a in toks:
                    aspect_weights[a] += 1.0
        # normalize
        total = sum(aspect_weights.values()) or 1.0
        for a in aspect_weights:
            aspect_weights[a] /= total

        # neighbor influence (no social graph -> approximate with global average user prior)
        if neighbor_weight > 0.0:
            neighbor_leniency = self.indexer.global_mean
            baseline = (1 - neighbor_weight) * baseline + neighbor_weight * neighbor_leniency

        verbosity_prior = min(1.0, 0.5 + 0.1 * len(texts))
        style = "formal" if baseline <= 3.0 else "enthusiastic"
        style_vector = {"formal": 1.0 if style == "formal" else 0.2, "enthusiastic": 1.0 if style == "enthusiastic" else 0.2}
        recent_sent_bias = 0.0
        return PersonaProfile(
            user_id=user_id,
            baseline_leniency=baseline,
            verbosity_prior=verbosity_prior,
            tone_style_prior=style,
            domain_familiarity=min(1.0, 0.1 * len(texts)),
            leniency_drift=0.0,
            aspect_preference_weights=aspect_weights,
            style_vector=style_vector,
            recent_sentiment_bias=recent_sent_bias,
        )


# ------------------------------
# Item Profiler
# ------------------------------

@dataclass
class ItemProfile:
    item_id: str
    quality_prior: float
    aspect_summary: Dict[str, float]
    domain_tags: List[str]
    freshness_score: float
    controversy: float
    aspect_confidence: float


class ItemProfiler:
    def __init__(self, indexer: DataIndexer, reputation_inertia: float = 0.5):
        self.indexer = indexer
        self.reputation_inertia = reputation_inertia

    def build(self, item_id: str) -> ItemProfile:
        texts = self.indexer.get_item_history_texts(item_id)
        prior = self.indexer.get_item_prior(item_id)
        # aspect summary
        aspect_summary: Dict[str, float] = {a: 0.0 for a in self.indexer.aspect_vocab}
        sentiments: List[float] = []
        for t in texts:
            s = sentiment_score(t)
            sentiments.append(s)
            toks = tokenize(t)
            for a in self.indexer.aspect_vocab:
                if a in toks:
                    aspect_summary[a] += 1.0
        # normalize to probabilities
        total = sum(aspect_summary.values()) or 1.0
        for a in aspect_summary:
            aspect_summary[a] /= total

        # controversy as variance of stars for item if available
        star_vals = [self.indexer.records[i].stars for i in self.indexer.item_index.get(item_id, []) if self.indexer.records[i].stars is not None]
        if star_vals:
            mean = sum(star_vals) / len(star_vals)
            var = sum((x - mean) ** 2 for x in star_vals) / len(star_vals)
        else:
            var = 0.0

        domain_tags = [a for a, w in aspect_summary.items() if w > 0.1][:3]
        aspect_conf = min(1.0, 0.1 * len(texts))
        freshness = min(1.0, 0.05 * len(texts))
        return ItemProfile(
            item_id=item_id,
            quality_prior=prior * (1 - self.reputation_inertia) + self.indexer.get_item_prior(item_id) * self.reputation_inertia,
            aspect_summary=aspect_summary,
            domain_tags=domain_tags,
            freshness_score=freshness,
            controversy=var,
            aspect_confidence=aspect_conf,
        )


# ------------------------------
# Plan Composer
# ------------------------------

@dataclass
class Plan:
    planned_aspects: List[str]
    tone_targets: str
    length_target: int


class PlanComposer:
    def __init__(self, aspect_selection_rules: Optional[Dict[str, Any]] = None):
        self.rules = aspect_selection_rules or {}

    def compose(
        self,
        persona: PersonaProfile,
        item: ItemProfile,
        platform_policy: Dict[str, Any],
        aspect_topk: int,
        ctx_merge_weight: float,
        length_target_mean: int,
        plan_diversity_temp: float,
    ) -> Plan:
        # blend persona and item aspect distributions
        blended: Dict[str, float] = {}
        for a in item.aspect_summary.keys():
            pv = persona.aspect_preference_weights.get(a, 0.0)
            iv = item.aspect_summary.get(a, 0.0)
            blended[a] = ctx_merge_weight * pv + (1 - ctx_merge_weight) * iv

        # sample top-k aspects with diversity via temperature
        def softmax(d: Dict[str, float], temp: float) -> Dict[str, float]:
            m = max(d.values()) if d else 0.0
            exps = {k: math.exp((v - m) / max(1e-6, temp)) for k, v in d.items()}
            s = sum(exps.values()) or 1.0
            return {k: v / s for k, v in exps.items()}

        probs = softmax(blended, max(1e-6, plan_diversity_temp))
        aspects_sorted = sorted(probs.items(), key=lambda kv: kv[1], reverse=True)
        planned = [a for a, _ in aspects_sorted[:max(1, aspect_topk)]]

        # tone target based on persona leniency and item prior
        expected = 0.5 * (persona.baseline_leniency / 5.0) + 0.5 * (item.quality_prior / 5.0)
        tone = "positive" if expected >= 0.6 else "neutral" if expected >= 0.45 else "negative"

        # length target
        min_s = platform_policy.get("min_sentences", 2)
        max_s = platform_policy.get("max_sentences", 6)
        lt = int(round(length_target_mean))
        lt = min(max(lt, min_s), max_s)
        return Plan(planned_aspects=planned, tone_targets=tone, length_target=lt)


# ------------------------------
# Review Author (LLM)
# ------------------------------

@dataclass
class AuthorPolicy:
    generation_guidelines: str = "Platform-safe, concise, specific, avoid profanity."
    style_alignment_weight: float = 0.7
    temperature_schedule: float = 0.5
    max_revision_loops: int = 1


class ReviewAuthor:
    def __init__(self, policy: Optional[AuthorPolicy] = None):
        self.policy = policy or AuthorPolicy()
        self.last_generated_text_quality_score: float = 0.0
        self.revision_count: int = 0

    def _build_prompt(self, plan: Plan, persona: PersonaProfile, item_ctx: ItemProfile, platform_policy: Dict[str, Any]) -> str:
        aspects_str = ", ".join(plan.planned_aspects) if plan.planned_aspects else "general impressions"
        prompt = (
            f"You are writing a product review.\n"
            f"Platform policy: {platform_policy.get('style')}. "
            f"Target length: {plan.length_target} sentences. Tone: {plan.tone_targets}.\n"
            f"Persona: user_id={persona.user_id}; baseline_leniency={persona.baseline_leniency:.2f}; "
            f"style={persona.tone_style_prior}; domain_familiarity={persona.domain_familiarity:.2f}.\n"
            f"Item: item_id={item_ctx.item_id}; prior_quality={item_ctx.quality_prior:.2f}; "
            f"domain_tags={', '.join(item_ctx.domain_tags) if item_ctx.domain_tags else 'general'}.\n"
            f"Plan:\n- Cover aspects: {aspects_str}\n- Be {plan.tone_targets} and specific with examples.\n"
            f"Guidelines: {self.policy.generation_guidelines}\n"
            f"Write the review now without including headings or bullet points."
        )
        return prompt

    def generate(
        self,
        plan: Plan,
        persona: PersonaProfile,
        item_ctx: ItemProfile,
        platform_policy: Dict[str, Any],
        llm_temperature: float,
        style_alignment_weight: float,
        model: str = "gpt-5",
        max_tokens: int = 512,
    ) -> str:
        # Build composite prompt and invoke the LLM
        prompt = self._build_prompt(plan, persona, item_ctx, platform_policy)
        # Encode additional hints in the prompt since we cannot directly set temperature via Responses API here
        prompt += f"\nWhen choosing wording, align {int(100*style_alignment_weight)}% to persona style. Avoid generic fluff."
        text = call_gpt5_with_responses_api(prompt=prompt, model=model, max_output_tokens=max_tokens)
        # Simple post-processing: clamp sentence count to target if drastically off (truncate)
        sents = re.split(r"(?<=[.!?])\s+", text.strip())
        if len(sents) > max(2 * plan.length_target, plan.length_target + 3):
            text = " ".join(sents[:max(1, plan.length_target + 1)])
        return text


# ------------------------------
# Star Rater
# ------------------------------

@dataclass
class RatingParams:
    mapping_slope: float
    mapping_intercept: float
    user_bias_weight: float
    item_bias_weight: float
    uncertainty_scale: float


class StarRater:
    def __init__(self, indexer: DataIndexer, params: RatingParams):
        self.indexer = indexer
        self.params = params

    def rate(self, text: str, user_id: str, item_id: str) -> int:
        s = sentiment_score(text)  # [0,1]
        # logistic mapping from sentiment to [1,5]
        def sigmoid(x: float) -> float:
            return 1.0 / (1.0 + math.exp(-x))
        user_prior = self.indexer.get_user_prior(user_id) - 3.0
        item_prior = self.indexer.get_item_prior(item_id) - 3.0
        z = self.params.mapping_slope * (s - 0.5) + self.params.mapping_intercept
        z += self.params.user_bias_weight * user_prior + self.params.item_bias_weight * item_prior
        expected = 1.0 + 4.0 * sigmoid(z)
        noise = random.gauss(0.0, self.params.uncertainty_scale * 0.2)
        val = expected + noise
        stars = int(round(min(5.0, max(1.0, val))))
        return stars


# ------------------------------
# QA Consistency
# ------------------------------

@dataclass
class QAParams:
    consistency_threshold: float
    max_auto_fix_attempts: int
    penalty_weight_style_violations: float


@dataclass
class QAResult:
    text: str
    stars: int
    consistency_score: float
    aspect_coverage: float
    length_deviation: float


class QAConsistency:
    def __init__(self, platform_policy: Dict[str, Any], params: QAParams):
        self.platform_policy = platform_policy
        self.params = params
        self.consistency_score: float = 1.0
        self.auto_fix_attempts: int = 0

    def evaluate(self, text: str, stars: int, plan: Plan) -> Tuple[float, float, float]:
        # Sentiment vs rating agreement
        pol = sentiment_score(text)  # [0,1]
        target_bucket = (stars - 1) / 4.0  # 0..1
        sent_agree = 1.0 - min(1.0, abs(pol - target_bucket) / 0.5)  # 1 when close; 0 when far

        # Aspect coverage: proportion of planned aspects mentioned
        toks = set(tokenize(text))
        covered = sum(1 for a in plan.planned_aspects if a in toks)
        aspect_cov = covered / max(1, len(plan.planned_aspects))

        # Length deviation
        sc = sentence_count(text)
        len_dev = abs(sc - plan.length_target)
        return sent_agree, aspect_cov, float(len_dev)

    def check_and_fix(
        self,
        text: str,
        stars: int,
        plan: Plan,
        author: ReviewAuthor,
        persona: PersonaProfile,
        item_ctx: ItemProfile,
    ) -> QAResult:
        self.auto_fix_attempts = 0
        sent_agree, aspect_cov, len_dev = self.evaluate(text, stars, plan)
        style_penalty = 0.0
        # simple style constraints
        if sentence_count(text) < self.platform_policy.get("min_sentences", 2):
            style_penalty += self.params.penalty_weight_style_violations
        if sentence_count(text) > self.platform_policy.get("max_sentences", 6):
            style_penalty += self.params.penalty_weight_style_violations
        consistency = max(0.0, min(1.0, 0.6 * sent_agree + 0.3 * aspect_cov + 0.1 * (1.0 - min(1.0, len_dev / 3.0)) - style_penalty))

        while consistency < self.params.consistency_threshold and self.auto_fix_attempts < self.params.max_auto_fix_attempts:
            self.auto_fix_attempts += 1
            # Nudge tone in prompt based on discrepancy
            pol = sentiment_score(text)
            target_bucket = (stars - 1) / 4.0
            if pol < target_bucket:
                plan.tone_targets = "more positive"
            else:
                plan.tone_targets = "more critical"
            # Regenerate
            text = author.generate(plan, persona, item_ctx, self.platform_policy, llm_temperature=0.4, style_alignment_weight=author.policy.style_alignment_weight, max_tokens=256)
            sent_agree, aspect_cov, len_dev = self.evaluate(text, stars, plan)
            consistency = max(0.0, min(1.0, 0.6 * sent_agree + 0.3 * aspect_cov + 0.1 * (1.0 - min(1.0, len_dev / 3.0)) - style_penalty))

        return QAResult(text=text, stars=stars, consistency_score=consistency, aspect_coverage=aspect_cov, length_deviation=len_dev)


# ------------------------------
# Parameter Tuner and Evaluator
# ------------------------------

@dataclass
class SimParams:
    neighbor_weight: float
    ctx_merge_weight: float
    aspect_topk: int
    length_target_mean: int
    plan_diversity_temp: float
    llm_temperature: float
    style_alignment_weight: float
    mapping_slope: float
    mapping_intercept: float
    user_bias_weight: float
    item_bias_weight: float
    uncertainty_scale: float
    consistency_threshold: float
    max_auto_fix_attempts: int
    objective_weights: Dict[str, float]


class Evaluator:
    def __init__(self):
        self.metrics: Dict[str, float] = {}
        self.by_segment: Dict[str, Dict[str, float]] = {}

    @staticmethod
    def compute_metrics(records: List[Dict[str, Any]]) -> Dict[str, float]:
        # records contain: gt_stars, gen_stars, gt_text, gen_text, qa fields
        star_pairs = [(r.get("gt_stars"), r.get("gen_stars")) for r in records if r.get("gt_stars") is not None and r.get("gen_stars") is not None]
        mae = sum(abs(a - b) for a, b in star_pairs) / max(1, len(star_pairs)) if star_pairs else 0.0
        rmse = math.sqrt(sum((a - b) ** 2 for a, b in star_pairs) / max(1, len(star_pairs))) if star_pairs else 0.0
        sim_vals = [jaccard_similarity(r.get("gt_text", "") or "", r.get("gen_text", "") or "") for r in records]
        text_sim = sum(sim_vals) / max(1, len(sim_vals)) if sim_vals else 0.0
        sent_agree_vals = []
        for r in records:
            pol = sentiment_score(r.get("gen_text", "") or "")
            bucket = ((r.get("gen_stars", 3)) - 1) / 4.0
            sent_agree_vals.append(1.0 - min(1.0, abs(pol - bucket) / 0.5))
        sent_agree = sum(sent_agree_vals) / max(1, len(sent_agree_vals)) if sent_agree_vals else 0.0
        aspect_cov_vals = [r.get("qa", {}).get("aspect_coverage", 0.0) for r in records]
        aspect_cov = sum(aspect_cov_vals) / max(1, len(aspect_cov_vals)) if aspect_cov_vals else 0.0
        consistency_vals = [r.get("qa", {}).get("consistency_score", 0.0) for r in records]
        consistency = sum(consistency_vals) / max(1, len(consistency_vals)) if consistency_vals else 0.0
        len_dev_vals = [r.get("qa", {}).get("length_deviation", 0.0) for r in records]
        len_dev = sum(len_dev_vals) / max(1, len(len_dev_vals)) if len_dev_vals else 0.0
        return {
            "RMSE_stars": rmse,
            "MAE_stars": mae,
            "Text_Similarity": text_sim,
            "Sentiment_Agreement": sent_agree,
            "Aspect_Coverage": aspect_cov,
            "Consistency_Score": consistency,
            "Length_Deviation": len_dev,
        }

    def evaluate(self, records: List[Dict[str, Any]]) -> Dict[str, float]:
        self.metrics = self.compute_metrics(records)
        return self.metrics


class ParameterTuner:
    def __init__(self, num_trials: int = 5, early_stop_patience: int = 3):
        self.num_trials = num_trials
        self.early_stop_patience = early_stop_patience
        self.best_params: Optional[SimParams] = None
        self.best_objective: float = float("inf")
        self.history: List[Tuple[SimParams, float]] = []

    @staticmethod
    def sample_params() -> SimParams:
        def ru(a: float, b: float) -> float:
            return random.uniform(a, b)
        def ri(a: int, b: int) -> int:
            return random.randint(a, b)
        # objective weights sampling and normalization
        w_stars = ru(0.4, 0.8)
        w_text = ru(0.2, 0.6)
        w_cons = ru(0.0, 0.3)
        s = w_stars + w_text + w_cons
        ow = {"stars": w_stars / s, "text": w_text / s, "consistency": w_cons / s}
        return SimParams(
            neighbor_weight=ru(0.0, 0.5),
            ctx_merge_weight=ru(0.2, 0.8),
            aspect_topk=ri(3, 6),
            length_target_mean=ri(2, 6),
            plan_diversity_temp=ru(0.3, 1.2),
            llm_temperature=ru(0.2, 0.9),
            style_alignment_weight=ru(0.3, 1.0),
            mapping_slope=ru(2.0, 8.0),
            mapping_intercept=ru(-2.0, 2.0),
            user_bias_weight=ru(0.0, 1.0),
            item_bias_weight=ru(0.0, 1.0),
            uncertainty_scale=ru(0.1, 1.0),
            consistency_threshold=ru(0.6, 0.9),
            max_auto_fix_attempts=ri(0, 2),
            objective_weights=ow,
        )

    def objective_for_trial(
        self,
        params: SimParams,
        indexer: DataIndexer,
        train_indices: List[int],
    ) -> float:
        # Run a fast simulation pass on training set and compute weighted loss
        author = ReviewAuthor(AuthorPolicy(style_alignment_weight=params.style_alignment_weight, max_revision_loops=params.max_auto_fix_attempts))
        persona_prof = PersonaProfiler(indexer)
        item_prof = ItemProfiler(indexer)
        rater = StarRater(indexer, RatingParams(
            mapping_slope=params.mapping_slope,
            mapping_intercept=params.mapping_intercept,
            user_bias_weight=params.user_bias_weight,
            item_bias_weight=params.item_bias_weight,
            uncertainty_scale=params.uncertainty_scale,
        ))
        qa = QAConsistency(indexer.platform_policy, QAParams(
            consistency_threshold=params.consistency_threshold,
            max_auto_fix_attempts=params.max_auto_fix_attempts,
            penalty_weight_style_violations=0.05,
        ))

        total_star_err = 0.0
        total_text_loss = 0.0
        total_cons_loss = 0.0
        count = 0
        # Limit to avoid excessive API calls during tuning
        max_train_eval = min(50, len(train_indices))
        sample_indices = random.sample(train_indices, max_train_eval) if len(train_indices) > max_train_eval else train_indices
        for idx in sample_indices:
            rec = indexer.records[idx]
            persona = persona_prof.build(rec.user_id, neighbor_weight=params.neighbor_weight)
            item = item_prof.build(rec.item_id)
            plan = PlanComposer().compose(
                persona, item, indexer.platform_policy,
                aspect_topk=params.aspect_topk,
                ctx_merge_weight=params.ctx_merge_weight,
                length_target_mean=params.length_target_mean,
                plan_diversity_temp=params.plan_diversity_temp,
            )
            gen_text = ReviewAuthor(author.policy).generate(
                plan, persona, item, indexer.platform_policy,
                llm_temperature=params.llm_temperature,
                style_alignment_weight=params.style_alignment_weight,
                max_tokens=256,
            )
            pred_stars = rater.rate(gen_text, rec.user_id, rec.item_id)
            qa_res = qa.check_and_fix(gen_text, pred_stars, plan, author, persona, item)

            # Loss components
            if rec.stars is not None:
                total_star_err += abs(rec.stars - qa_res.stars)
            ref_text = rec.review or ""
            sim = jaccard_similarity(ref_text, qa_res.text)
            total_text_loss += (1.0 - sim)
            total_cons_loss += (1.0 - qa_res.consistency_score)
            count += 1

        if count == 0:
            return float("inf")
        w = params.objective_weights
        objective = w["stars"] * (total_star_err / count) + w["text"] * (total_text_loss / count) + w["consistency"] * (total_cons_loss / count)
        return objective

    def tune(self, indexer: DataIndexer) -> SimParams:
        train_indices = indexer.split_index.get("train", list(range(len(indexer.records))))
        patience = 0
        for t in range(self.num_trials):
            params = self.sample_params()
            obj = self.objective_for_trial(params, indexer, train_indices)
            self.history.append((params, obj))
            if obj < self.best_objective:
                self.best_objective = obj
                self.best_params = params
                patience = 0
            else:
                patience += 1
            if patience >= self.early_stop_patience:
                break
        assert self.best_params is not None
        return self.best_params


# ------------------------------
# Simulation runner
# ------------------------------

def run_simulation(indexer: DataIndexer, params: SimParams, split: str) -> List[Dict[str, Any]]:
    indices = indexer.split_index.get(split, [])
    author = ReviewAuthor(AuthorPolicy(style_alignment_weight=params.style_alignment_weight, max_revision_loops=params.max_auto_fix_attempts))
    persona_prof = PersonaProfiler(indexer)
    item_prof = ItemProfiler(indexer)
    rater = StarRater(indexer, RatingParams(
        mapping_slope=params.mapping_slope,
        mapping_intercept=params.mapping_intercept,
        user_bias_weight=params.user_bias_weight,
        item_bias_weight=params.item_bias_weight,
        uncertainty_scale=params.uncertainty_scale,
    ))
    qa = QAConsistency(indexer.platform_policy, QAParams(
        consistency_threshold=params.consistency_threshold,
        max_auto_fix_attempts=params.max_auto_fix_attempts,
        penalty_weight_style_violations=0.05,
    ))
    traces: List[Dict[str, Any]] = []
    for idx in indices:
        rec = indexer.records[idx]
        persona = persona_prof.build(rec.user_id, neighbor_weight=params.neighbor_weight)
        item = item_prof.build(rec.item_id)
        plan = PlanComposer().compose(
            persona, item, indexer.platform_policy,
            aspect_topk=params.aspect_topk,
            ctx_merge_weight=params.ctx_merge_weight,
            length_target_mean=params.length_target_mean,
            plan_diversity_temp=params.plan_diversity_temp,
        )
        gen_text = author.generate(
            plan, persona, item, indexer.platform_policy,
            llm_temperature=params.llm_temperature,
            style_alignment_weight=params.style_alignment_weight,
            max_tokens=256,
        )
        pred_stars = rater.rate(gen_text, rec.user_id, rec.item_id)
        qa_res = qa.check_and_fix(gen_text, pred_stars, plan, author, persona, item)

        trace = {
            "user_id": rec.user_id,
            "item_id": rec.item_id,
            "gt_stars": rec.stars,
            "gt_text": rec.review,
            "gen_text": qa_res.text,
            "gen_stars": qa_res.stars,
            "plan": {
                "aspects": plan.planned_aspects,
                "tone": plan.tone_targets,
                "length_target": plan.length_target,
            },
            "persona": {
                "baseline_leniency": persona.baseline_leniency,
                "style": persona.tone_style_prior,
            },
            "item": {
                "quality_prior": item.quality_prior,
                "domain_tags": item.domain_tags,
            },
            "qa": {
                "consistency_score": qa_res.consistency_score,
                "aspect_coverage": qa_res.aspect_coverage,
                "length_deviation": qa_res.length_deviation,
            },
        }
        traces.append(trace)
    return traces


def default_params() -> SimParams:
    # Reasonable defaults in the middle of ranges if tuning is skipped
    ow = {"stars": 0.6, "text": 0.3, "consistency": 0.1}
    return SimParams(
        neighbor_weight=0.1,
        ctx_merge_weight=0.5,
        aspect_topk=4,
        length_target_mean=4,
        plan_diversity_temp=0.7,
        llm_temperature=0.5,
        style_alignment_weight=0.7,
        mapping_slope=4.0,
        mapping_intercept=0.0,
        user_bias_weight=0.4,
        item_bias_weight=0.4,
        uncertainty_scale=0.3,
        consistency_threshold=0.7,
        max_auto_fix_attempts=1,
        objective_weights=ow,
    )


def main():
    try:
        set_global_seed(42)
        indexer = DataIndexer.load_from_file_or_synthetic()
        # Tune parameters on training set
        num_trials = int(os.environ.get("NUM_TRIALS", "5"))
        tuner = ParameterTuner(num_trials=num_trials, early_stop_patience=3)
        best_params = tuner.tune(indexer)

        # Persist calibrated parameters
        calibrated = {
            "params": best_params.__dict__,
            "global_mean_star": indexer.global_mean,
            "user_priors": indexer.user_priors,
            "item_priors": indexer.item_priors,
            "timestamp": time.time(),
        }
        write_json("calibrated_parameters.json", calibrated)

        # Run simulation on validation split
        val_traces = run_simulation(indexer, best_params, split="test")
        write_jsonl("simulation_traces.jsonl", val_traces)

        # Evaluate
        evaluator = Evaluator()
        metrics = evaluator.evaluate(val_traces)
        write_json("evaluation_metrics.json", metrics)

        # Optional ablation report (placeholder)
        ablation = {
            "note": "Ablation not implemented; this placeholder can be extended.",
            "modes": [],
        }
        write_json("ablation_report.json", ablation)

        # Also simulate training for diagnostic purposes (optional)
        train_traces = run_simulation(indexer, best_params, split="train")
        # We won't write train traces by default to keep outputs minimal, uncomment if needed:
        # write_jsonl("simulation_traces_train.jsonl", train_traces)

        print("Calibration objective:", tuner.best_objective)
        print("Validation metrics:", json.dumps(metrics, indent=2))
    except Exception as e:
        print("Fatal error in main():", e, file=sys.stderr)
        traceback.print_exc()
        sys.exit(1)


# Execute main for both direct execution and sandbox wrapper invocation
main()